[package]
name = "esthri"
version = "0.1.0"
authors = ["Jason Mobarak <jason@swift-nav.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.41"
rusoto_s3 = "0.41"
ctrlc = "3.1"
once_cell = "1.2"
rust-crypto = "0.2"
hex = "0.4"
structopt = "0.3"
