release = true
publish = false
push = true
consolidate-commits = false
pre-release-commit-message = "release: {{crate_name}}: version {{version}}"
tag-message = "Esthri version {{tag_name}}"
tag-prefix = ""
tag-name = "{{version}}"
tag = true
